version: '2'
services:
  web:
      container_name: server
      build: .
      volumes:
        - ./:/server
      ports:
        - "80:3000"
      links:
        - shankDB
      tty: true
  shankDB:
      container_name: db
      image: mongo:3.4.2
      ports:
        - "27017:27017"
      command: mongod --smallfiles --quiet
      environment :
        - MONGODB_DATABASE="shank"
      tty: true
